# Generated by Django 3.2.18 on 2023-05-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20230504_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
