# Generated by Django 3.2.18 on 2023-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_category_en_us',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='Имя категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(default='Текст отсутствует', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(default='Текст отсутствует', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='Имя категории', max_length=64, unique=True),
        ),
    ]
