# Generated by Django 3.2.18 on 2023-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20230630_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='category name', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_en_us',
            field=models.CharField(help_text='category name', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='category name', max_length=64, null=True, unique=True),
        ),
    ]
